-- Gqeberha 2026 community trips
-- price_cents remains aligned to community_price_cents for compatibility with existing app logic.
-- non_community_price_cents stores the first-time / guest price.
-- original_price_cents is reserved for optional promo compare pricing and is left null here.

insert into public.cities (
  slug,
  name,
  province,
  tagline,
  active
)
values (
  'gqeberha',
  'Gqeberha',
  'Eastern Cape',
  'Coastal escapes, tastings, hikes, and hosted community experiences.',
  true
)
on conflict (slug) do update
set
  name = excluded.name,
  province = excluded.province,
  tagline = excluded.tagline,
  active = excluded.active;

with selected_city as (
  select id
  from public.cities
  where slug = 'gqeberha'
  limit 1
)
insert into public.trips (
  city_id,
  slug,
  title,
  category,
  image_url,
  summary,
  meeting_point,
  start_date,
  end_date,
  duration,
  price_cents,
  community_price_cents,
  non_community_price_cents,
  original_price_cents,
  deposit_cents,
  capacity,
  seats_remaining,
  status,
  featured,
  tags,
  published,
  pickup_points,
  is_special,
  special_collection_slug
)
select
  selected_city.id,
  seed.slug,
  seed.title,
  seed.category,
  null,
  seed.summary,
  null,
  seed.start_date,
  seed.end_date,
  seed.duration,
  seed.price_cents,
  seed.price_cents,
  seed.non_community_price_cents,
  null,
  seed.deposit_cents,
  seed.capacity,
  seed.capacity,
  'OPEN'::public.trip_status,
  false,
  seed.tags,
  true,
  '{}'::text[],
  true,
  'freshers-community-2026'
from selected_city
cross join (
  values
    (
      'gqeberha-overnight-hike-camp-2026-10-10',
      'Overnight Hike & Camp',
      'Community Experience',
      'Freshers Community overnight hiking and camping escape with guided trail support, meals, and host coordination.',
      date '2026-10-10',
      date '2026-10-11',
      '2 days / 1 night',
      110000,
      121000,
      30000,
      24,
      array['freshers-community', 'gqeberha', 'hike', 'camping', 'overnight']
    ),
    (
      'gqeberha-scenic-hike-breakfast-2026-03-07',
      'Scenic Hike + Breakfast',
      'Community Experience',
      'Guided scenic hike with permits, breakfast, transport, and a hosted Freshers Community day out.',
      date '2026-03-07',
      null,
      'Day trip',
      35000,
      38500,
      10000,
      30,
      array['freshers-community', 'gqeberha', 'hike', 'breakfast']
    ),
    (
      'gqeberha-sip-paint-charcuterie-2026-03-21',
      'Sip & Paint + Cheese & Charcuterie Platter',
      'Community Experience',
      'Studio-led sip and paint session with supplies, curated platter, welcome drink, and hosted transport.',
      date '2026-03-21',
      null,
      'Day trip',
      65000,
      71500,
      20000,
      24,
      array['freshers-community', 'gqeberha', 'sip-and-paint', 'charcuterie']
    ),
    (
      'gqeberha-craft-distilled-honey-tasting-2026-05-09',
      'Craft Distilled Experience & Honey Tasting Workshop',
      'Community Experience',
      'Craft distilled tasting experience with pairings, seasonal honey tasting workshop, transport, and host support.',
      date '2026-05-09',
      null,
      'Day trip',
      85000,
      90000,
      20000,
      22,
      array['freshers-community', 'gqeberha', 'tasting', 'honey', 'workshop']
    ),
    (
      'gqeberha-sip-paint-culinary-combo-2026-05-30',
      'Sip & Paint + Culinary Experience Combo',
      'Community Experience',
      'Creative studio session paired with tapas or finger foods, welcome drink, hosted transport, and social community energy.',
      date '2026-05-30',
      null,
      'Day trip',
      85000,
      93500,
      25000,
      24,
      array['freshers-community', 'gqeberha', 'sip-and-paint', 'culinary']
    ),
    (
      'gqeberha-hike-braai-chill-2026-06-27',
      'Hike, Braai & Chill',
      'Community Experience',
      'Guided hike followed by a relaxed braai social with transport, permits, and hosted coordination included.',
      date '2026-06-27',
      null,
      'Day trip',
      60000,
      66000,
      15000,
      30,
      array['freshers-community', 'gqeberha', 'hike', 'braai']
    ),
    (
      'gqeberha-quad-bike-wilderness-2026-07-11',
      'Quad Bike Wilderness',
      'Community Experience',
      'Outdoor quad bike adventure with safety gear, briefing, transport, and a dedicated experience host.',
      date '2026-07-11',
      null,
      'Day trip',
      110000,
      121000,
      30000,
      20,
      array['freshers-community', 'gqeberha', 'quad-bike', 'adventure']
    ),
    (
      'gqeberha-scenic-hike-breakfast-2026-08-01',
      'Scenic Hike + Breakfast',
      'Community Experience',
      'Guided scenic hike with breakfast, permits, transport, and Freshers Community host support.',
      date '2026-08-01',
      null,
      'Day trip',
      38000,
      40000,
      12000,
      30,
      array['freshers-community', 'gqeberha', 'hike', 'breakfast']
    ),
    (
      'gqeberha-horse-riding-organic-lunch-2026-09-26',
      'Horse Riding & Organic Lunch',
      'Community Experience',
      'Horse riding day experience with safety briefing, organic lunch, transport, and community host support.',
      date '2026-09-26',
      null,
      'Day trip',
      110000,
      121000,
      20000,
      20,
      array['freshers-community', 'gqeberha', 'horse-riding', 'lunch']
    ),
    (
      'gqeberha-strawberry-picking-2026-10-31',
      'Strawberry Picking',
      'Community Experience',
      'Freshers Community farm day with transport, entry, strawberry picking, and experience host support.',
      date '2026-10-31',
      null,
      'Day trip',
      65000,
      71500,
      10000,
      28,
      array['freshers-community', 'gqeberha', 'farm', 'strawberry-picking']
    ),
    (
      'gqeberha-spirit-of-africa-gala-dinner-2026-11-21',
      'Spirit of Africa Gala Dinner',
      'Community Experience',
      'Hosted gala evening with African dinner, entertainment, transport, and Freshers Community social atmosphere.',
      date '2026-11-21',
      null,
      'Evening experience',
      85000,
      93500,
      20000,
      26,
      array['freshers-community', 'gqeberha', 'gala-dinner', 'entertainment']
    )
) as seed(
  slug,
  title,
  category,
  summary,
  start_date,
  end_date,
  duration,
  price_cents,
  non_community_price_cents,
  deposit_cents,
  capacity,
  tags
)
on conflict (slug) do update
set
  city_id = excluded.city_id,
  title = excluded.title,
  category = excluded.category,
  image_url = excluded.image_url,
  summary = excluded.summary,
  meeting_point = excluded.meeting_point,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  duration = excluded.duration,
  price_cents = excluded.price_cents,
  community_price_cents = excluded.community_price_cents,
  non_community_price_cents = excluded.non_community_price_cents,
  original_price_cents = excluded.original_price_cents,
  deposit_cents = excluded.deposit_cents,
  capacity = excluded.capacity,
  seats_remaining = excluded.capacity,
  status = excluded.status,
  featured = excluded.featured,
  tags = excluded.tags,
  published = excluded.published,
  pickup_points = excluded.pickup_points,
  is_special = excluded.is_special,
  special_collection_slug = excluded.special_collection_slug;

-- Gqeberha 2026 Trailblazers Community trips
with selected_city as (
  select id
  from public.cities
  where slug = 'gqeberha'
  limit 1
)
insert into public.trips (
  city_id,
  slug,
  title,
  category,
  image_url,
  summary,
  meeting_point,
  start_date,
  end_date,
  duration,
  price_cents,
  community_price_cents,
  non_community_price_cents,
  original_price_cents,
  deposit_cents,
  capacity,
  seats_remaining,
  status,
  featured,
  tags,
  published,
  pickup_points,
  is_special,
  special_collection_slug
)
select
  selected_city.id,
  seed.slug,
  seed.title,
  seed.category,
  null,
  seed.summary,
  null,
  seed.start_date,
  seed.end_date,
  seed.duration,
  seed.price_cents,
  seed.price_cents,
  seed.non_community_price_cents,
  null,
  seed.deposit_cents,
  seed.capacity,
  seed.capacity,
  'OPEN'::public.trip_status,
  false,
  seed.tags,
  true,
  '{}'::text[],
  true,
  'trailblazers-community-2026'
from selected_city
cross join (
  values
    (
      'gqeberha-kenton-on-sea-getaway-2026-08-08',
      'Kenton on Sea Getaway',
      'Community Experience',
      'Trailblazers Community coastal getaway with transport, 2 nights accommodation, meals, activities, and host support.',
      date '2026-08-08',
      date '2026-08-10',
      '3 days / 2 nights',
      270000,
      286000,
      50000,
      24,
      array['trailblazers-community', 'gqeberha', 'kenton-on-sea', 'getaway', 'overnight']
    ),
    (
      'gqeberha-scenic-hike-breakfast-2026-02-28-trailblazers',
      'Scenic Hike + Breakfast',
      'Community Experience',
      'Guided scenic hike with breakfast, permits, transport, and Trailblazers Community host support.',
      date '2026-02-28',
      null,
      'Day trip',
      38000,
      40000,
      10000,
      30,
      array['trailblazers-community', 'gqeberha', 'hike', 'breakfast']
    ),
    (
      'gqeberha-game-drive-two-course-lunch-2026-03-14',
      'Game Drive & 2-Course Lunch',
      'Community Experience',
      'Guided game drive with park access, 2-course lunch, transport, and Trailblazers Community host support.',
      date '2026-03-14',
      null,
      'Day trip',
      115000,
      126500,
      20000,
      22,
      array['trailblazers-community', 'gqeberha', 'game-drive', 'lunch']
    ),
    (
      'gqeberha-rifle-range-outdoors-2026-04-11',
      'Rifle Range & Outdoors',
      'Community Experience',
      'Outdoor rifle range experience with safety briefing, braai, transport, and Trailblazers Community host support.',
      date '2026-04-11',
      null,
      'Day trip',
      55000,
      60500,
      15000,
      20,
      array['trailblazers-community', 'gqeberha', 'rifle-range', 'outdoors']
    ),
    (
      'gqeberha-quad-bike-wilderness-2026-05-23',
      'Quad Bike Wilderness',
      'Community Experience',
      'Quad bike outdoor experience with safety gear, briefing, transport, and Trailblazers Community host support.',
      date '2026-05-23',
      null,
      'Day trip',
      110000,
      121000,
      30000,
      20,
      array['trailblazers-community', 'gqeberha', 'quad-bike', 'adventure']
    ),
    (
      'gqeberha-sand-river-waterfall-hike-2026-06-13',
      'Sand River Waterfall Hike',
      'Community Experience',
      'Guided waterfall hike with permits, transport, and Trailblazers Community host support.',
      date '2026-06-13',
      null,
      'Day trip',
      40000,
      44000,
      10000,
      28,
      array['trailblazers-community', 'gqeberha', 'waterfall', 'hike']
    ),
    (
      'gqeberha-maitlands-beach-games-2026-07-04',
      'Maitlands Beach Games',
      'Community Experience',
      'Beach games social with transport, snacks, water, host support, and community prizes or giveaways.',
      date '2026-07-04',
      null,
      'Day trip',
      49900,
      54890,
      25000,
      30,
      array['trailblazers-community', 'gqeberha', 'beach-games', 'maitlands']
    ),
    (
      'gqeberha-st-francis-canal-lifestyle-cruise-2026-07-25',
      'St Francis Canal Lifestyle Cruise',
      'Community Experience',
      'Canal cruise lifestyle experience with skipper, welcome drink, light snacks, transport, and Trailblazers Community host support.',
      date '2026-07-25',
      null,
      'Day trip',
      99900,
      109890,
      30000,
      24,
      array['trailblazers-community', 'gqeberha', 'canal-cruise', 'st-francis']
    ),
    (
      'gqeberha-hike-braai-chill-2026-08-29',
      'Hike, Braai & Chill',
      'Community Experience',
      'Guided hike and braai social with transport, permits, and Trailblazers Community host support.',
      date '2026-08-29',
      null,
      'Day trip',
      50000,
      55000,
      15000,
      30,
      array['trailblazers-community', 'gqeberha', 'hike', 'braai']
    ),
    (
      'gqeberha-strawberry-picking-2026-10-31-trailblazers',
      'Strawberry Picking',
      'Community Experience',
      'Farm entry and strawberry picking day with transport and Trailblazers Community host support.',
      date '2026-10-31',
      null,
      'Day trip',
      65000,
      71500,
      10000,
      28,
      array['trailblazers-community', 'gqeberha', 'farm', 'strawberry-picking']
    ),
    (
      'gqeberha-spirit-of-africa-gala-dinner-2026-11-21-trailblazers',
      'Spirit of Africa Gala Dinner',
      'Community Experience',
      'Hosted gala evening with African dinner, 3-course meal, entertainment, transport, and Trailblazers Community host support.',
      date '2026-11-21',
      null,
      'Evening experience',
      85000,
      93500,
      20000,
      26,
      array['trailblazers-community', 'gqeberha', 'gala-dinner', 'entertainment']
    )
) as seed(
  slug,
  title,
  category,
  summary,
  start_date,
  end_date,
  duration,
  price_cents,
  non_community_price_cents,
  deposit_cents,
  capacity,
  tags
)
on conflict (slug) do update
set
  city_id = excluded.city_id,
  title = excluded.title,
  category = excluded.category,
  image_url = excluded.image_url,
  summary = excluded.summary,
  meeting_point = excluded.meeting_point,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  duration = excluded.duration,
  price_cents = excluded.price_cents,
  community_price_cents = excluded.community_price_cents,
  non_community_price_cents = excluded.non_community_price_cents,
  original_price_cents = excluded.original_price_cents,
  deposit_cents = excluded.deposit_cents,
  capacity = excluded.capacity,
  seats_remaining = excluded.capacity,
  status = excluded.status,
  featured = excluded.featured,
  tags = excluded.tags,
  published = excluded.published,
  pickup_points = excluded.pickup_points,
  is_special = excluded.is_special,
  special_collection_slug = excluded.special_collection_slug;

-- Gqeberha 2026 Adventurers Community trips
with selected_city as (
  select id
  from public.cities
  where slug = 'gqeberha'
  limit 1
)
insert into public.trips (
  city_id,
  slug,
  title,
  category,
  image_url,
  summary,
  meeting_point,
  start_date,
  end_date,
  duration,
  price_cents,
  community_price_cents,
  non_community_price_cents,
  original_price_cents,
  deposit_cents,
  capacity,
  seats_remaining,
  status,
  featured,
  tags,
  published,
  pickup_points,
  is_special,
  special_collection_slug
)
select
  selected_city.id,
  seed.slug,
  seed.title,
  seed.category,
  null,
  seed.summary,
  null,
  seed.start_date,
  seed.end_date,
  seed.duration,
  seed.price_cents,
  seed.price_cents,
  seed.non_community_price_cents,
  null,
  seed.deposit_cents,
  seed.capacity,
  seed.capacity,
  'OPEN'::public.trip_status,
  false,
  seed.tags,
  true,
  '{}'::text[],
  true,
  'adventurers-community-2026'
from selected_city
cross join (
  values
    (
      'gqeberha-port-alfred-weekend-away-2026-04-03',
      'Port Alfred Weekend Away',
      'Community Experience',
      'Adventurers Community weekend away with transport, 2 nights accommodation, all meals, activities, and host support.',
      date '2026-04-03',
      date '2026-04-05',
      '3 days / 2 nights',
      240000,
      264000,
      50000,
      24,
      array['adventurers-community', 'gqeberha', 'weekend-away', 'port-alfred', 'overnight']
    ),
    (
      'gqeberha-scenic-hike-breakfast-2026-02-28',
      'Scenic Hike + Breakfast',
      'Community Experience',
      'Guided scenic hike with permits, breakfast, transport, and hosted Adventurers Community coordination.',
      date '2026-02-28',
      null,
      'Day trip',
      38000,
      40000,
      10000,
      30,
      array['adventurers-community', 'gqeberha', 'hike', 'breakfast']
    ),
    (
      'gqeberha-sip-paint-culinary-combo-2026-03-21',
      'Sip & Paint + Culinary Experience Combo',
      'Community Experience',
      'Studio-led creative session with tapas or finger foods, welcome drink, transport, and Adventurers Community host support.',
      date '2026-03-21',
      null,
      'Day trip',
      75000,
      82500,
      20000,
      24,
      array['adventurers-community', 'gqeberha', 'sip-and-paint', 'culinary']
    ),
    (
      'gqeberha-sunset-river-cruise-party-2026-04-18',
      'Sunset River Cruise Party',
      'Community Experience',
      'Sunset cruise social with transport, entertainment, welcome drink, and hosted Adventurers Community vibes.',
      date '2026-04-18',
      null,
      'Day trip',
      95000,
      104500,
      25000,
      26,
      array['adventurers-community', 'gqeberha', 'cruise', 'sunset-party']
    ),
    (
      'gqeberha-tsitsikama-waterfall-hike-braai-2026-05-16',
      'Tsitsikama Waterfall, Hike & Braai',
      'Community Experience',
      'Waterfall visit with guided hike, permits, braai, transport, and Adventurers Community host support.',
      date '2026-05-16',
      null,
      'Day trip',
      58000,
      63800,
      10000,
      28,
      array['adventurers-community', 'gqeberha', 'tsitsikama', 'hike', 'braai']
    ),
    (
      'gqeberha-art-culinary-fusion-paint-pizza-party-2026-07-18',
      'Art & Culinary Fusion: Paint & Pizza Party',
      'Community Experience',
      'Paint and pizza social with art supplies, soft drink, music, transport, and Adventurers Community host support.',
      date '2026-07-18',
      null,
      'Day trip',
      65000,
      71500,
      15000,
      24,
      array['adventurers-community', 'gqeberha', 'paint-party', 'pizza']
    ),
    (
      'gqeberha-sunset-catamaran-soirees-2026-08-22',
      'Sunset Catamaran Soirees',
      'Community Experience',
      'Catamaran sunset cruise with skipper and crew, welcome drink, snacks, music, transport, and host support.',
      date '2026-08-22',
      null,
      'Day trip',
      95000,
      104500,
      10000,
      24,
      array['adventurers-community', 'gqeberha', 'catamaran', 'sunset']
    ),
    (
      'gqeberha-safari-culinary-experience-2026-09-12',
      'Safari & Culinary Experience',
      'Community Experience',
      'Guided safari or game drive with park access, 2-course meal, transport, and Adventurers Community host support.',
      date '2026-09-12',
      null,
      'Day trip',
      105000,
      115500,
      20000,
      22,
      array['adventurers-community', 'gqeberha', 'safari', 'culinary']
    ),
    (
      'gqeberha-bloukrans-bungy-zipline-2026-10-17',
      'Bloukrans Bungy & Zipline',
      'Community Experience',
      'High-adrenaline experience with transport, bungy jump, zipline, safety gear, media, lunch, and host support.',
      date '2026-10-17',
      null,
      'Day trip',
      240000,
      264000,
      45000,
      18,
      array['adventurers-community', 'gqeberha', 'bloukrans', 'bungy', 'zipline']
    ),
    (
      'gqeberha-scenic-hike-breakfast-2026-11-07',
      'Scenic Hike + Breakfast',
      'Community Experience',
      'Guided scenic hike with breakfast, permits, transport, and Adventurers Community host support.',
      date '2026-11-07',
      null,
      'Day trip',
      38000,
      40000,
      10000,
      30,
      array['adventurers-community', 'gqeberha', 'hike', 'breakfast']
    ),
    (
      'gqeberha-spirit-of-africa-gala-dinner-2026-11-21-adventurers',
      'Spirit of Africa Gala Dinner',
      'Community Experience',
      'Hosted gala evening with African dinner, live entertainment, transport, and Adventurers Community social atmosphere.',
      date '2026-11-21',
      null,
      'Evening experience',
      85000,
      93500,
      20000,
      26,
      array['adventurers-community', 'gqeberha', 'gala-dinner', 'entertainment']
    )
) as seed(
  slug,
  title,
  category,
  summary,
  start_date,
  end_date,
  duration,
  price_cents,
  non_community_price_cents,
  deposit_cents,
  capacity,
  tags
)
on conflict (slug) do update
set
  city_id = excluded.city_id,
  title = excluded.title,
  category = excluded.category,
  image_url = excluded.image_url,
  summary = excluded.summary,
  meeting_point = excluded.meeting_point,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  duration = excluded.duration,
  price_cents = excluded.price_cents,
  community_price_cents = excluded.community_price_cents,
  non_community_price_cents = excluded.non_community_price_cents,
  original_price_cents = excluded.original_price_cents,
  deposit_cents = excluded.deposit_cents,
  capacity = excluded.capacity,
  seats_remaining = excluded.capacity,
  status = excluded.status,
  featured = excluded.featured,
  tags = excluded.tags,
  published = excluded.published,
  pickup_points = excluded.pickup_points,
  is_special = excluded.is_special,
  special_collection_slug = excluded.special_collection_slug;
